### ISSUE TITLE
error

### ISSUE THREAD

**Issue by watchbit** [BaseMax/bonbast-api#7]
hi.
The bonbast.com website returned unsupported homepage response Please fill an issue in https://github.com/BaseMax/bonbast-api/issues/new

**Comment by BaseMax** [comment]
Heya, Can you send more details?

**Comment by watchbit** [comment]
when I run code, I get this message:
The bonbast.com website returned unsupported homepage response Please fill an issue in https://github.com/BaseMax/bonbast-api/issues/new

link: https://watchbit.ir/api/bb/example.php

**Comment by alinezamifar** [comment]
i have get this error also .

**Comment by watchbit** [comment]
Hi, is there a solution?

**Comment by BaseMax** [comment]
Fixed and it's working again like a charm!

Happy to help.

Let me know if you need more.
